### PR TITLE
add support for pve decklist

### PR DESCRIPTION
**Pull request by sebastientromp**
For the "new" modes, starting with Dungeon Run.

For now I'm only returning the decklist (this is what I'm needing today), but we can add support for other info as the need arises.

### CODE REVIEW

**Comment by sebastientromp** [comment]
* I've found a bug in the current implementation. The DeckCards field in memory doesn't behave as I thought it would so getting the actual decklist is more complex than I thought. But I think I have it now :)
* I'll try and update the code of this PR to match what you did in #7

**Comment by sebastientromp** [comment]
Both items above are fixed, the PR should be ready to be merged now :)

**Comment by sebastientromp** [comment]
Rebase from master done, ready to merge :)

**Comment by hackf5** [comment]
image

It looks like the `HackF5.UnitySpy.HearthstoneLib.Detail.Deck` namespace got missed when you checked in on this branch. Can you take a look to see what's going on? Thanks.

**Comment by sebastientromp** [comment]
Hey sorry, I messed up when rebasing between the branches. I have removed the Deck package, it will arrive in the next PR :)

**Pull request merged**
